version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_book_store
    environment:
      POSTGRES_USER: book_store_admin
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
