version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my_postgres_db_minimal
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata_minimal:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata_minimal:
